spring:
  application:
    name: critter
  lifecycle:
    timeout-per-shutdown-phase: 60s
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: INFO

server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"

  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoint:
    health:
      show-details: "always"